TypeError: 'tuple' object is not callable
